create type public.crm_role as enum ('admin', 'operator', 'viewer');

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.crm_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  contact_name text not null,
  segment text not null,
  source text not null,
  instagram_profile text,
  stage text not null,
  owner_id uuid not null references public.profiles(user_id),
  estimated_value numeric(12, 2) not null default 0,
  recurring_value numeric(12, 2),
  probability smallint not null default 0 check (probability between 0 and 100),
  next_action text not null,
  next_action_at timestamptz not null,
  loss_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.commercial_tasks (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.leads(id) on delete cascade,
  title text not null,
  due_at timestamptz not null,
  priority text not null check (priority in ('Alta', 'Média', 'Baixa')),
  completed boolean not null default false,
  owner_id uuid not null references public.profiles(user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.crm_events (
  id bigint generated by default as identity primary key,
  lead_id uuid references public.leads(id) on delete cascade,
  actor_id uuid not null references public.profiles(user_id),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

create trigger commercial_tasks_set_updated_at
before update on public.commercial_tasks
for each row execute function public.set_updated_at();

create or replace function public.current_crm_role()
returns public.crm_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where user_id = auth.uid();
$$;

revoke all on function public.current_crm_role() from public;
grant execute on function public.current_crm_role() to authenticated;

alter table public.profiles enable row level security;
alter table public.leads enable row level security;
alter table public.commercial_tasks enable row level security;
alter table public.crm_events enable row level security;

create policy "authenticated users read profiles"
on public.profiles for select
to authenticated
using (true);

create policy "administrators manage profiles"
on public.profiles for all
to authenticated
using (public.current_crm_role()::text in ('admin', 'operator'))
with check (public.current_crm_role()::text in ('admin', 'operator'));

create policy "authenticated users read leads"
on public.leads for select
to authenticated
using (true);

create policy "administrators manage leads"
on public.leads for all
to authenticated
using (public.current_crm_role()::text in ('admin', 'operator'))
with check (public.current_crm_role()::text in ('admin', 'operator'));

create policy "authenticated users read tasks"
on public.commercial_tasks for select
to authenticated
using (true);

create policy "administrators manage tasks"
on public.commercial_tasks for all
to authenticated
using (public.current_crm_role()::text in ('admin', 'operator'))
with check (public.current_crm_role()::text in ('admin', 'operator'));

create policy "authenticated users read events"
on public.crm_events for select
to authenticated
using (true);

create policy "administrators create events"
on public.crm_events for insert
to authenticated
with check (
  public.current_crm_role()::text in ('admin', 'operator')
  and actor_id = auth.uid()
);

create index leads_stage_idx on public.leads(stage);
create index leads_next_action_at_idx on public.leads(next_action_at);
create index tasks_due_at_idx on public.commercial_tasks(due_at);
create index crm_events_lead_id_idx on public.crm_events(lead_id);

