-- Keep this migration safe when Supabase applies same-day files in lexical order.
alter table public.whatsapp_conversations
  add column if not exists qualification_status text not null default 'new';

create table if not exists public.crm_funnel_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in (
      'conversation_created',
      'conversation_status_changed',
      'conversation_lead_linked',
      'lead_created',
      'lead_stage_changed'
    )
  ),
  event_key text unique,
  conversation_id uuid references public.whatsapp_conversations(id) on delete cascade,
  lead_id uuid references public.leads(id) on delete cascade,
  from_status text,
  to_status text,
  from_stage text,
  to_stage text,
  actor_id uuid references public.profiles(user_id) on delete set null,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint crm_funnel_events_entity_check
    check (conversation_id is not null or lead_id is not null)
);

create index if not exists crm_funnel_events_conversation_idx
  on public.crm_funnel_events(conversation_id, occurred_at asc);

create index if not exists crm_funnel_events_lead_idx
  on public.crm_funnel_events(lead_id, occurred_at asc);

create index if not exists crm_funnel_events_type_idx
  on public.crm_funnel_events(event_type, occurred_at asc);

alter table public.crm_funnel_events enable row level security;

drop policy if exists "authenticated users read funnel events" on public.crm_funnel_events;
create policy "authenticated users read funnel events"
on public.crm_funnel_events for select
to authenticated
using (true);

create or replace function public.record_whatsapp_funnel_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.crm_funnel_events (
      event_type,
      event_key,
      conversation_id,
      to_status,
      actor_id,
      occurred_at
    ) values (
      'conversation_created',
      'conversation:' || new.id::text || ':created',
      new.id,
      new.qualification_status,
      auth.uid(),
      coalesce(new.created_at, now())
    )
    on conflict (event_key) do nothing;

  elsif old.qualification_status is distinct from new.qualification_status then
    insert into public.crm_funnel_events (
      event_type,
      conversation_id,
      from_status,
      to_status,
      actor_id,
      occurred_at
    ) values (
      'conversation_status_changed',
      new.id,
      old.qualification_status,
      new.qualification_status,
      auth.uid(),
      now()
    );
  end if;

  if tg_op = 'UPDATE' and old.lead_id is distinct from new.lead_id and new.lead_id is not null then
    insert into public.crm_funnel_events (
      event_type,
      event_key,
      conversation_id,
      lead_id,
      actor_id,
      occurred_at
    ) values (
      'conversation_lead_linked',
      'conversation:' || new.id::text || ':lead:' || new.lead_id::text,
      new.id,
      new.lead_id,
      auth.uid(),
      now()
    )
    on conflict (event_key) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists whatsapp_conversations_record_funnel_event
  on public.whatsapp_conversations;
create trigger whatsapp_conversations_record_funnel_event
after insert or update of qualification_status, lead_id
on public.whatsapp_conversations
for each row execute function public.record_whatsapp_funnel_event();

create or replace function public.record_lead_funnel_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.crm_funnel_events (
      event_type,
      event_key,
      lead_id,
      to_stage,
      actor_id,
      occurred_at
    ) values (
      'lead_created',
      'lead:' || new.id::text || ':created',
      new.id,
      new.stage,
      auth.uid(),
      coalesce(new.created_at, now())
    )
    on conflict (event_key) do nothing;

  elsif old.stage is distinct from new.stage then
    insert into public.crm_funnel_events (
      event_type,
      lead_id,
      from_stage,
      to_stage,
      actor_id,
      occurred_at
    ) values (
      'lead_stage_changed',
      new.id,
      old.stage,
      new.stage,
      auth.uid(),
      now()
    );
  end if;

  return new;
end;
$$;

drop trigger if exists leads_record_funnel_event on public.leads;
create trigger leads_record_funnel_event
after insert or update of stage
on public.leads
for each row execute function public.record_lead_funnel_event();

insert into public.crm_funnel_events (
  event_type,
  event_key,
  conversation_id,
  to_status,
  occurred_at
)
select
  'conversation_created',
  'conversation:' || conversation.id::text || ':created',
  conversation.id,
  conversation.qualification_status,
  conversation.created_at
from public.whatsapp_conversations as conversation
on conflict (event_key) do nothing;

insert into public.crm_funnel_events (
  event_type,
  event_key,
  lead_id,
  to_stage,
  occurred_at
)
select
  'lead_created',
  'lead:' || lead.id::text || ':created',
  lead.id,
  lead.stage,
  lead.created_at
from public.leads as lead
on conflict (event_key) do nothing;

insert into public.crm_funnel_events (
  event_type,
  event_key,
  conversation_id,
  lead_id,
  occurred_at
)
select
  'conversation_lead_linked',
  'conversation:' || conversation.id::text || ':lead:' || conversation.lead_id::text,
  conversation.id,
  conversation.lead_id,
  conversation.updated_at
from public.whatsapp_conversations as conversation
where conversation.lead_id is not null
on conflict (event_key) do nothing;
